# Generated by Django 4.1.3 on 2022-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_user_is_customer_remove_user_is_mistri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('Mistri', 'Mistri')], default=None, max_length=120),
        ),
    ]
