# Generated by Django 4.1.3 on 2022-12-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('Mistri', 'Mistri')], default='choice Your Type', max_length=120),
        ),
    ]
