# Generated by Django 4.1.3 on 2022-12-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aggre',
            field=models.BooleanField(default=False),
        ),
    ]
