# Generated by Django 4.1.3 on 2022-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_profile_aggre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='add_more_skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('electic', 'electic'), ('tv', 'tv'), ('mobail', 'mobail'), ('microwave', 'microwave'), ('carmechaig', 'carmechaig'), ('freezer', 'frezzer'), ('computer', 'computer'), ('printer', 'printer'), ('plumber', 'plumber'), ('color-prainter', 'color-prainter'), ('rajmisrti', 'rajmisrti'), ('katmistri', 'katmistri')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
