# Generated by Django 4.1.3 on 2022-12-09 15:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_profile_add_more_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_more_subject',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bangla', 'Bangla'), ('english', 'English'), ('math', 'Math'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('highermath', 'Highermath'), ('ict', 'ICT'), ('biology', 'Biology'), ('financialaccounting', 'Financial Accounting')], default=False, max_length=25, null=True),
        ),
    ]
