# Generated by Django 4.1.3 on 2022-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_aggre_profile_mistri_profile_tutor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mistri',
            new_name='aggre',
        ),
    ]
