# Generated by Django 4.1.3 on 2022-12-09 17:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_profile_add_more_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_more_clases',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('class 1', 'claas 1'), ('class 2', 'claas 2'), ('class 3', 'claas 3'), ('class 4', 'claas 4'), ('class 5', 'claas 5'), ('class 6', 'claas 6'), ('class 7', 'claas 7'), ('class 8', 'claas 8'), ('class 9', 'claas 9'), ('class 10', 'claas 10'), ('Inter First year', 'Inter First year'), ('Inter Second Year', 'Inter Second Year')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_more_subject',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Highermath', 'Highermath'), ('ICT', 'ICT'), ('Biology', 'Biology'), ('Financial Accounting', 'Financial Accounting')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clases',
            field=models.CharField(choices=[('class 1', 'claas 1'), ('class 2', 'claas 2'), ('class 3', 'claas 3'), ('class 4', 'claas 4'), ('class 5', 'claas 5'), ('class 6', 'claas 6'), ('class 7', 'claas 7'), ('class 8', 'claas 8'), ('class 9', 'claas 9'), ('class 10', 'claas 10'), ('Inter First year', 'Inter First year'), ('Inter Second Year', 'Inter Second Year')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Highermath', 'Highermath'), ('ICT', 'ICT'), ('Biology', 'Biology'), ('Financial Accounting', 'Financial Accounting')], max_length=100),
        ),
    ]
