# Generated by Django 4.1.3 on 2022-12-14 07:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_more_skill',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ইলেক্টিক', 'ইলেক্টিক'), ('টিভি', 'টিভি'), ('মোবাইল', 'মোবাইল'), ('কম্পিউটার', 'কম্পিউটার'), ('পিন্টার', 'পিন্টার'), ('কার মেকানিক', 'কার মেকানিক'), ('ফ্রিজ', 'ফ্রিজ'), ('এসি', 'এসি'), ('সিসিটিভি', 'সিসিটিভি'), ('প্লাম্বার', 'প্লাম্বার'), ('রং মিস্ত্রী', 'রং মিস্ত্রী'), ('কাঠ মিস্ত্রী', 'কাঠ মিস্ত্রী'), ('রাজ মিস্ত্রী', 'রাজ মিস্ত্রী'), ('ভিডিওগ্রাফার', 'ভিডিওগ্রাফার')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(choices=[('ইলেক্টিক', 'ইলেক্টিক'), ('টিভি', 'টিভি'), ('মোবাইল', 'মোবাইল'), ('কম্পিউটার', 'কম্পিউটার'), ('পিন্টার', 'পিন্টার'), ('কার মেকানিক', 'কার মেকানিক'), ('ফ্রিজ', 'ফ্রিজ'), ('এসি', 'এসি'), ('সিসিটিভি', 'সিসিটিভি'), ('প্লাম্বার', 'প্লাম্বার'), ('রং মিস্ত্রী', 'রং মিস্ত্রী'), ('কাঠ মিস্ত্রী', 'কাঠ মিস্ত্রী'), ('রাজ মিস্ত্রী', 'রাজ মিস্ত্রী'), ('ভিডিওগ্রাফার', 'ভিডিওগ্রাফার')], max_length=50),
        ),
    ]
