# Generated by Django 4.1.3 on 2022-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='আমি কাস্টমার'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mistri',
            field=models.BooleanField(default=False, verbose_name='আমি মিস্ত্রী'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='আমি টিউটর'),
        ),
    ]
